/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : PortaA.c
**     Project   : quest3mcp
**     Processor : MC9S12C128CFU16
**     Component : ByteIO
**     Version   : Component 02.058, Driver 03.14, CPU db: 2.87.411
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 01/07/2023, 21:04
**     Abstract  :
**         This component "ByteIO" implements an one-byte input/output.
**         It uses one 8-bit port.
**         Note: This component is set to work in Input direction only.
**         Methods of this component are mostly implemented as a macros 
**         (if supported by target langauage and compiler).
**     Settings  :
**         Port name                   : A
**
**         Initial direction           : Input (direction cannot be changed)
**         Initial output value        : 0 = 000H
**         Initial pull option         : up
**
**         8-bit data register         : PORTA     [$0000]
**         8-bit control register      : DDRA      [$0002]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    41   |   PA0_ADDR8_DATA8
**                    1      |    42   |   PA1_ADDR9_DATA9
**                    2      |    43   |   PA2_ADDR10_DATA10
**                    3      |    44   |   PA3_ADDR11_DATA11
**                    4      |    45   |   PA4_ADDR12_DATA12
**                    5      |    46   |   PA5_ADDR13_DATA13
**                    6      |    47   |   PA6_ADDR14_DATA14
**                    7      |    48   |   PA7_ADDR15_DATA15
**             ----------------------------------------------------
**     Contents  :
**         GetDir - bool PortaA_GetDir(void);
**         GetVal - byte PortaA_GetVal(void);
**         GetBit - bool PortaA_GetBit(byte Bit);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE PortaA. */

#include "PortaA.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma DATA_SEG PortaA_DATA           /* Select data segment "PortaA_DATA" */
#pragma CODE_SEG PortaA_CODE
#pragma CONST_SEG PortaA_CONST         /* Constant section for this module */
/*
** ===================================================================
**     Method      :  PortaA_GetMsk (component ByteIO)
**
**     Description :
**         The method returns a bit mask which corresponds to the 
**         required bit position.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static const byte PortaA_Table[8U] = {
  0x01U, 0x02U, 0x04U, 0x08U, 0x10U, 0x20U, 0x40U, 0x80U
};                                     /* Table of mask constants */

static byte PortaA_GetMsk (byte PinIndex)
{
  return (byte)((PinIndex<8U) ? PortaA_Table[PinIndex] : 0U); /* Check range and return appropriate bit mask */
}

/*
** ===================================================================
**     Method      :  PortaA_GetVal (component ByteIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pins and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Input direction only.
**     Parameters  : None
**     Returns     :
**         ---        - Input value (0 to 255)
** ===================================================================
*/
/*
byte PortaA_GetVal(void)

**  This method is implemented as a macro. See PortaA.h file.  **
*/

/*
** ===================================================================
**     Method      :  PortaA_GetBit (component ByteIO)
**
**     Description :
**         This method returns the specified bit of the input value.
**           a) direction = Input  : reads the input value from pins
**                                   and returns the specified bit
**           b) direction = Output : returns the specified bit
**                                   of the last written value
**         Note: This component is set to work in Input direction only.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to read (0 to 7)
**     Returns     :
**         ---        - Value of the specified bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
** ===================================================================
*/
bool PortaA_GetBit(byte Bit)
{
  byte const Mask = PortaA_GetMsk(Bit); /* Temporary variable - bit mask to test */
  return (bool)(((getReg8(PORTA) & Mask) == Mask) ? 1U : 0U); /* Test if specified bit of port data register is set */
}

/*
** ===================================================================
**     Method      :  PortaA_GetDir (component ByteIO)
**
**     Description :
**         This method returns direction of the component.
**     Parameters  : None
**     Returns     :
**         ---        - Direction of the component (always FALSE, Input only)
**                      FALSE = Input, TRUE = Output
** ===================================================================
*/
/*
bool PortaA_GetDir(void)

**  This method is implemented as a macro. See PortaA.h file.  **
*/


/* END PortaA. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
