/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : PortaB.c
**     Project   : quest3mcp
**     Processor : MC9S12C128CFU16
**     Component : ByteIO
**     Version   : Component 02.058, Driver 03.14, CPU db: 2.87.411
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 01/07/2023, 21:04
**     Abstract  :
**         This component "ByteIO" implements an one-byte input/output.
**         It uses one 8-bit port.
**         Note: This component is set to work in Output direction only.
**         Methods of this component are mostly implemented as a macros 
**         (if supported by target langauage and compiler).
**     Settings  :
**         Port name                   : B
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0 = 000H
**         Initial pull option         : up
**
**         8-bit data register         : PORTB     [$0001]
**         8-bit control register      : DDRB      [$0003]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    16   |   PB0_ADDR0_DATA0
**                    1      |    17   |   PB1_ADDR1_DATA1
**                    2      |    18   |   PB2_ADDR2_DATA2
**                    3      |    19   |   PB3_ADDR3_DATA3
**                    4      |    20   |   PB4_ADDR4_DATA4
**                    5      |    21   |   PB5_ADDR5_DATA5
**                    6      |    22   |   PB6_ADDR6_DATA6
**                    7      |    23   |   PB7_ADDR7_DATA7
**             ----------------------------------------------------
**     Contents  :
**         GetDir - bool PortaB_GetDir(void);
**         GetVal - byte PortaB_GetVal(void);
**         PutVal - void PortaB_PutVal(byte Val);
**         GetBit - bool PortaB_GetBit(byte Bit);
**         PutBit - void PortaB_PutBit(byte Bit, bool Val);
**         SetBit - void PortaB_SetBit(byte Bit);
**         ClrBit - void PortaB_ClrBit(byte Bit);
**         NegBit - void PortaB_NegBit(byte Bit);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE PortaB. */

#include "PortaB.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma DATA_SEG PortaB_DATA           /* Select data segment "PortaB_DATA" */
#pragma CODE_SEG PortaB_CODE
#pragma CONST_SEG PortaB_CONST         /* Constant section for this module */
/*
** ===================================================================
**     Method      :  PortaB_GetMsk (component ByteIO)
**
**     Description :
**         The method returns a bit mask which corresponds to the 
**         required bit position.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static const byte PortaB_Table[8U] = {
  0x01U, 0x02U, 0x04U, 0x08U, 0x10U, 0x20U, 0x40U, 0x80U
};                                     /* Table of mask constants */

static byte PortaB_GetMsk (byte PinIndex)
{
  return (byte)((PinIndex<8U) ? PortaB_Table[PinIndex] : 0U); /* Check range and return appropriate bit mask */
}

/*
** ===================================================================
**     Method      :  PortaB_GetVal (component ByteIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pins and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---        - Input value (0 to 255)
** ===================================================================
*/
/*
byte PortaB_GetVal(void)

**  This method is implemented as a macro. See PortaB.h file.  **
*/

/*
** ===================================================================
**     Method      :  PortaB_PutVal (component ByteIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 255)
**     Returns     : Nothing
** ===================================================================
*/
/*
void PortaB_PutVal(byte Val)

**  This method is implemented as a macro. See PortaB.h file.  **
*/

/*
** ===================================================================
**     Method      :  PortaB_GetBit (component ByteIO)
**
**     Description :
**         This method returns the specified bit of the input value.
**           a) direction = Input  : reads the input value from pins
**                                   and returns the specified bit
**           b) direction = Output : returns the specified bit
**                                   of the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to read (0 to 7)
**     Returns     :
**         ---        - Value of the specified bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
** ===================================================================
*/
bool PortaB_GetBit(byte Bit)
{
  byte const Mask = PortaB_GetMsk(Bit); /* Temporary variable - bit mask to test */
  return (bool)(((getReg8(PORTB) & Mask) == Mask) ? 1U : 0U); /* Test if specified bit of port data register is set */
}

/*
** ===================================================================
**     Method      :  PortaB_PutBit (component ByteIO)
**
**     Description :
**         This method writes the new value to the specified bit
**         of the output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit (0 to 7)
**         Val        - New value of the bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
**     Returns     : Nothing
** ===================================================================
*/
void PortaB_PutBit(byte Bit, bool Val)
{
  byte const Mask = PortaB_GetMsk(Bit); /* Temporary variable - put bit mask */
  if (Val) {
    setReg8Bits(PORTB, Mask);          /* [bit Bit]=0x01U */
  } else { /* !Val */
    clrReg8Bits(PORTB, Mask);          /* [bit Bit]=0x00U */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  PortaB_SetBit (component ByteIO)
**
**     Description :
**         This method sets (sets to one) the specified bit of the
**         output value.
**         [ It is the same as "PutBit(Bit,TRUE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to set (0 to 7)
**     Returns     : Nothing
** ===================================================================
*/
void PortaB_SetBit(byte Bit)
{
  byte const Mask = PortaB_GetMsk(Bit); /* Temporary variable - set bit mask */
  setReg8Bits(PORTB, Mask);            /* [bit Bit]=0x01U */
}

/*
** ===================================================================
**     Method      :  PortaB_ClrBit (component ByteIO)
**
**     Description :
**         This method clears (sets to zero) the specified bit
**         of the output value.
**         [ It is the same as "PutBit(Bit,FALSE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to clear (0 to 7)
**     Returns     : Nothing
** ===================================================================
*/
void PortaB_ClrBit(byte Bit)
{
  byte const Mask = PortaB_GetMsk(Bit); /* Temporary variable - set bit mask */
  clrReg8Bits(PORTB, Mask);            /* [bit Bit]=0x00U */
}

/*
** ===================================================================
**     Method      :  PortaB_NegBit (component ByteIO)
**
**     Description :
**         This method negates (inverts) the specified bit of the
**         output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to invert (0 to 7)
**     Returns     : Nothing
** ===================================================================
*/
void PortaB_NegBit(byte Bit)
{
  byte const Mask = PortaB_GetMsk(Bit); /* Temporary variable - set bit mask */
  invertReg8Bits(PORTB, Mask);         /* [bit Bit]=invert */
}

/*
** ===================================================================
**     Method      :  PortaB_GetDir (component ByteIO)
**
**     Description :
**         This method returns direction of the component.
**     Parameters  : None
**     Returns     :
**         ---        - Direction of the component (always TRUE, Output only)
**                      FALSE = Input, TRUE = Output
** ===================================================================
*/
/*
bool PortaB_GetDir(void)

**  This method is implemented as a macro. See PortaB.h file.  **
*/


/* END PortaB. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
